# Generated by Django 4.2.23 on 2025-07-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
    ]
