# Generated by Django 4.2.23 on 2025-07-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_due_date'),
        ('tasks', '0002_auto_20250725_1420'),
    ]

    operations = [
    ]
