# Generated by Django 4.2.23 on 2025-07-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_merge_20250725_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
